app/models/budget.py
#!/usr/bin/python3
"""

"""

from app import app, db
from datetime import datetime
from app.models import users

class Budget(db.Model):
    __tablename__ = 'budgets_table'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    budget_id = db.Column(db.String(200), nullable=False)
    amount = db.Column(db.Integer, nullable=False)
    date = db.Column(db.DateTime, nullable=False, default=datetime.now)
    purpose = db.Column(db.String(2000), nullable=False)
    bdgt_name = db.Column(db.String(100), nullable=False)
    status = db.Column(db.Integer, nullable=False, default=0)
    approved_by = db.Column(db.String(200), nullable=False, default='0')
    user_id = db.Column(db.Integer, db.ForeignKey(users.Users.id), nullable=False)
    transactions = db.relationship('Transaction', backref='budget_id', lazy=True)
    
    def __repr__(self):
        return f"Budget('{self.amount}', '{self.purpose}', '{self.bdgt_name}', '{self.status}', '{self.budget_id}', '{self.approved_by}')"

app/models/files.py
#!/usr/bin/python3
"""

"""

from app import db

class Files(db.Model):
    __tablename__ = 'files'
    id = db.Column(db.Integer, primary_key=True)
    file_no = db.Column(db.String(20), nullable=False)
    file_name = db.Column(db.String(20), nullable=False)
    subject = db.Column(db.String(300), nullable=False)
    file_fee = db.Column(db.Integer, nullable=False)
    transactions = db.relationship('Transaction', backref='file_no', lazy=True)
    
    def __repr__(self):
        return f"File('{self.id}', '{self.file_no}', '{self.file_name}', '{self.subject}', '{self.file_fee}')"

app/models/transactions.py
#!/usr/bin/python3
"""

"""

from app import app, db
from app.models import users, budget, files

class Transaction(db.Model):
    __tablename__ = 'transactions_table'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    transaction_id = db.Column(db.String(100), unique=True, nullable=False)
    # phone_no = db.Column(db.String(20), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey(users.Users.id), nullable=False)
    budget = db.Column(db.Integer, db.ForeignKey(budget.Budget.id), nullable=False)
    file = db.Column(db.String(20), db.ForeignKey(files.Files.file_no), nullable=False)
    amount = db.Column(db.Integer, nullable=False)
    narration = db.Column(db.String(200),nullable=True)
    trans_date = db.Column(db.DateTime(), nullable=False)
    status = db.Column(db.String(20), nullable=False)
    merchant_req_id = db.Column(db.String(40),nullable=True)
    mpesa_ref = db.Column(db.String(20),nullable=True)

    def __repr__(self):
        return f"Transaction('{self.transaction_id}', '{self.amount}', '{self.trans_date}', '{self.status}', '{self.merchant_req_id}', '{self.mpesa_ref}')"

app/views/budget/forms.py
#!/usr/bin/python3
"""

"""

from flask_wtf import FlaskForm
from flask_login import current_user
from wtforms import StringField, SubmitField, IntegerField
from wtforms.validators import DataRequired


class BudgetForm(FlaskForm):
    amount = IntegerField('Amount',
                           validators=[DataRequired()])
    
    name = StringField('Name', validators=[DataRequired()])
    
    purpose = StringField('Purpose', validators=[DataRequired()])

    submit = SubmitField('Submit')

app/views/files/forms.py
#!/usr/bin/python3
"""

"""

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField
from wtforms.validators import DataRequired

class FileForm(FlaskForm):

    file_no = StringField('File Number', validators=[DataRequired()])
    file_name = StringField('File Name', validators=[DataRequired()])
    subject = StringField('Subject', validators=[DataRequired()])
    file_fee = IntegerField('File Fees', validators=[DataRequired()])

    submit = SubmitField('Submit')

app/views/budget/routes.py
#!/usr/bin/python3
"""

"""


from flask import render_template, request, url_for, flash, redirect, abort, session, Blueprint
import uuid
from app import db, bcrypt
from app.views.budget.forms import BudgetForm
from app.models.budget import Budget
from app.models.transactions import Transaction
from datetime import datetime
from flask_login import login_user, current_user, logout_user, login_required
import json

budgetz = Blueprint('budgetz', __name__)


@budgetz.route('/budgets')
@login_required
def budgets():
    budgets = Budget.query.all()
    return render_template('budgets.html', page='budgets', title='Budgets', budgets=budgets)


@budgetz.route('/approvals')
@login_required
def approvals():
    budgets = Budget.query.filter(Budget.user_id != current_user.id).all()
    return render_template('approvals.html', page='approvals', title='Approvals', budgets=budgets)


@budgetz.route('/new_budget/new', methods=['POST', 'GET'])
@login_required
def create_budget():
    budgets = Budget.query.all()
    form = BudgetForm()
    bdgt_id = str(uuid.uuid4())
    available_funds = 100000
    funds_list = []
    for budget in budgets:
        budget_amount = budget.amount
        funds_list.append(budget_amount)
    budget_funds = sum(funds_list)

    
    if form.validate_on_submit():
        if available_funds >= budget_funds + form.amount.data:
            budget = Budget(budget_id=bdgt_id, amount=form.amount.data, bdgt_name=form.name.data, purpose=form.purpose.data, phone=current_user)
            db.session.add(budget)
            db.session.commit()
            flash('Your budget has been created. Await Approval!', 'success')
            return redirect(url_for('budgetz.budgets'))
        else:
            flash('Insufficient funds. Please top up account!', 'warning')
            return redirect(url_for('budgetz.create_budget'))
    return render_template('create_budget.html', page='budgets', title='Create New Budget',
                           form=form, legend='New Budget')
    

@budgetz.route("/budget/<int:budget_id>/update", methods=['POST', 'GET'])
def budget(budget_id):
    budget = Budget.query.get_or_404(budget_id)

    # ---------------------------------------------
    transactions = Transaction.query.filter_by(budget=budget_id).all()
    trans_amnt_list = []
    if transactions:
        for trans in transactions:
            trans_amount = trans.amount
            trans_amnt_list.append(trans_amount)
    utilised_funds = sum(trans_amnt_list)
    available_funds = budget.amount - utilised_funds
    # ---------------------------------------------

    purposeEditVal = json.loads(budget.purpose)
    urls = request.path
    urls = urls.split('/')
    urls = urls[-1]
    if budget.phone != current_user:
        abort(403)
    form = BudgetForm()
    if form.validate_on_submit():
        if budget.status == 1:
            flash('Your budget is Approved. You cannot Update!', 'warning')
            return redirect(url_for('budgetz.budgets'))
        else:
            budget.amount = form.amount.data
            budget.purpose = form.purpose.data
            budget.bdgt_name = form.name.data
            budget.status = 0
            db.session.commit()
            flash('Your budget has been Updated. Await Approval!', 'success')
            return redirect(url_for('budgetz.budgets'))
    elif request.method == 'GET':
        form.amount.data = budget.amount
        form.purpose.data = budget.purpose
        form.name.data = budget.bdgt_name
    return render_template('create_budget.html', page='budgets', title='Update Budget', available_funds=available_funds, budget=budget, edit_vals=purposeEditVal, url=urls, ad_class = 'disabled', form=form, del_id=budget.id, phone=budget.phone, legend='Update Budget')


@budgetz.route("/budget/<int:budget_id>/delete", methods=['POST'])
def delete_budget(budget_id):
    budget = Budget.query.get_or_404(budget_id)
    if budget.phone != current_user:
        abort(403)
    db.session.delete(budget)
    db.session.commit()
    flash('Your budget has been Deleted!', 'success')
    return redirect(url_for('budgetz.budgets'))


@budgetz.route('/budget/<int:budget_id>/view', methods=['GET'])
def view_budget(budget_id):
        
    form = BudgetForm()
    budget = Budget.query.get_or_404(budget_id)
    budget_ppse = json.loads(budget.purpose)
    budget_user = budget.phone.phone

    return render_template('confirm_budget.html', form=form, budget=budget, budget_ppse=budget_ppse, page='approvals', title='Confirm Budget', user=budget_user,
                           delete_bdgt='<a role="button" class="btn btn-outline-danger btn-sm" data-toggle="modal" data-target="#deleteModal">Delete Budget</a>')


@budgetz.route('/approvals/<int:budget_id>/confirm_budget/<string:approve_string>', methods=['POST', 'GET'])
def approve_budget(budget_id, approve_string):
        
    budget = Budget.query.get_or_404(budget_id)
    if approve_string == 'approve':
        budget.status = 1
        budget.approved_by = current_user.name
        db.session.commit()
        flash('Budget has been Approved!', 'success')
        return redirect(url_for('budgetz.approvals'))
    elif approve_string == 'disapprove':
        budget.status = 2
        budget.approved_by = current_user.name
        db.session.commit()
        flash('Budget has been Dispproved!', 'danger')
        return redirect(url_for('budgetz.approvals'))

app/views/files/routes.py
#!/usr/bin/python3

from flask import render_template, request, url_for, flash, redirect, abort, session, Blueprint
from app import db, bcrypt
from app.views.files.forms import FileForm
from app.models.files import Files
from app.models.transactions import Transaction
from datetime import datetime
from flask_login import login_user, current_user, logout_user, login_required

filez = Blueprint('filez', __name__)


@filez.route('/new_file/new', methods=['POST', 'GET'])
@login_required
def create_file():
    files = Files.query.all()

    form = FileForm()
    if form.validate_on_submit():
        file = Files(file_no=form.file_no.data, file_name=form.file_name.data, subject=form.subject.data, file_fee=form.file_fee.data)
        db.session.add(file)
        db.session.commit()
        flash('File created successfuly!', 'success')
        return redirect(url_for('filez.files'))
    elif request.method == 'GET':
        if len(files) == 0:
            form.file_no.data = '100/1/C'
        elif len(files) > 0:
            file_list = []
            def_val = 0
            for file in files:
                val = file.file_no
                val = val.split('/')
                no_val = val[0]
                file_list.append(no_val)
            initial_val = int(max(file_list))+1
            def_val = str(initial_val)+'/1/C'
            form.file_no.data = def_val
    return render_template('create_file.html', page='files', title='Create New file',
                           form=form, legend='New File')


@filez.route('/files')
@login_required
def files():
    
    files = Files.query.all()
    if len(files) == 0:
        count = 0
    else:
        count = len(files)

    return render_template('files.html', page='files', files=files, count=count)


@filez.route('/files/<int:file_id>/view', methods=['GET'])
def view_file(file_id):
        
    file_info = Files.query.get_or_404(file_id)
    fileName = file_info.file_name
    fileNo = file_info.file_no
    file_totals = []

    transactions_per_file = Transaction.query.filter_by(file=fileNo).all()
    for trns_cost in transactions_per_file:
        cost = trns_cost.amount
        file_totals.append(cost)
    
    file_costs = sum(file_totals)

    return render_template('view_file.html', file=file_info, page='files', title=fileNo+" - "+fileName, transactions=transactions_per_file, file_costs=file_costs)

app/views/transactions/routes.py
#!/usr/bin/python3

from flask import render_template, request, url_for, flash, redirect, abort, session, Blueprint
# from app import db, bcrypt
from app.models.transactions import Transaction
from flask_login import login_user, current_user, logout_user, login_required

transactionz = Blueprint('transactionz', __name__)


@transactionz.route('/transactions')
@login_required
def transactions():

    transactions = []
    bdgt_names = []

    if current_user.role == 'Admin':
        transactions = Transaction.query.all()
    else:
        transactions = Transaction.query.filter_by(user_id=current_user.id).all()

    for transaction in transactions:
        bdgt_names.append(transaction.budget)

    return render_template('transactions.html', page='transactions', transactions=transactions, names=bdgt_names)

app/views/users/routes.py
#!/usr/bin/python3

from flask import render_template, request, url_for, flash, redirect, abort, session, Blueprint
from app import app, db, bcrypt
from app.views.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from app.models.users import Users
from app.models.files import Files
from app.models.budget import Budget
from app.models.transactions import Transaction
from datetime import datetime
from flask_login import login_user, current_user, logout_user, login_required

users = Blueprint('users', __name__)




@users.route("/users")
def allUsers(): # ************************* users *************************
    users = Users.query.all()
    return render_template('users.html', page='users', users=users)


# ************************************* Home *************************************
@users.route('/home')
@login_required
def home():
    users_count = Users.query.count()
    files_count = Files.query.count()
    
    budget_count = Budget.query.filter(Budget.user_id == current_user.id).count()

    transactions = 0
    trans_title = ''
    if current_user.role == 'Admin':
        transactions = Transaction.query.count()
        trans_title = 'Transactions'
    else:
        transactions = Transaction.query.filter_by(user_id=current_user.id).count()
        trans_title = 'My Transactions'
    
    return render_template('home.html', page='home', user_count=users_count, files_count=files_count, budget_count=budget_count, transactions=transactions, trans_title=trans_title)

# ************************************* Home *************************************

@users.route('/account/<user_id>')
@login_required
def account(user_id):
    user = Users.query.get_or_404(user_id)
    # if user.phone != current_user:
    #     abort(403)
    return render_template('account.html', page='account', title='Account', user=user)



@users.route('/register', methods=['POST', 'GET'])
def register():
    # if current_user.is_authenticated:
    #     return redirect(url_for('home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        date_val = form.date.data
        date_value = datetime.strptime(date_val, "%Y-%m-%d")
        user = Users(name=form.name.data, email=form.email.data, phone=form.phone.data, role=form.role.data, password=hashed_pw, date=date_value)
        db.session.add(user)
        db.session.commit()
        flash(f'Account created for {form.name.data}!', 'success')
        return redirect(url_for('allUsers'))
    return render_template('register.html', page='register', title='Register', form=form)


@users.route("/user/<int:user_id>/update", methods=['POST', 'GET'])
def user(user_id):
    user = Users.query.get_or_404(user_id)
    
    form = UpdateUserForm()
    if form.validate_on_submit():

        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        date_val = form.date.data
        date_value = datetime.strptime(date_val, "%Y-%m-%d")

        user.name = form.name.data
        user.email = form.email.data
        user.phone = form.phone.data
        user.role = form.role.data
        if user == current_user:
            user.password = hashed_pw

        user.date = date_value

        db.session.commit()
        flash('User has been Updated!', 'success')
        return redirect(url_for('account', user_id=user.id))
    elif request.method == 'GET':
        form.name.data = user.name
        form.email.data = user.email
        form.phone.data = user.phone
        form.role.data = user.role
        form.id.data = user.id
        form.date.data = user.date.strftime('%Y-%m-%d')
    return render_template('register.html', page='users', title='Update user', form=form, del_id=user.id, user=user, legend='Update user')


@users.route("/user/<int:user_id>/delete", methods=['POST'])
def delete_user(user_id):
    user = Users.query.get_or_404(user_id)
    if current_user.role != 'Admin':
        abort(403)
    db.session.delete(user)
    db.session.commit()
    flash('User has been Deleted!', 'success')
    return redirect(url_for('allUsers'))


@users.route('/', methods=['POST', 'GET'])
@users.route('/login', methods=['POST', 'GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(phone=form.phone.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash(f'You have been logged in!', 'success')
            return redirect(next_page) if next_page else redirect(url_for('users.home'))
            # return redirect(url_for('home'))
        else:
            flash(f'Login Unsuccesseful. Check your details!', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))

app/templates/account.html
{% extends "page_template.html" %}
{% block contents %}

<div class="content">

    <section class="places">

        {% if user.phone == current_user.phone or current_user.role == 'Admin' %}
            <div class="card w-50">
                <div class="card-body">
                    {% if current_user.role == 'Admin' and user.phone != current_user.phone %}
                        <h5 class="card-title">{{ user.name }}'s Account</h5>
                    {% elif user.phone == current_user.phone %}
                        <h5 class="card-title">My Profile</h5>
                    {% endif %}
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><b>Name:</b> {{ user.name }}</li>
                        <li class="list-group-item"><b>Email:</b> {{ user.email }}</li>
                        <li class="list-group-item"><b>Phone:</b> {{ user.phone }}</li>
                        <li class="list-group-item"><b>Role:</b> {{ user.role }}</li>
                    </ul>
                    <div class="form-group row">
                        <div class="col-sm-9">
                            <a role="button" href="{{ url_for('users.user', user_id=user.id) }}" class="btn btn-outline-warning btn-sm mt-3 pb-0">Edit Profile</a>
                        </div>
                        <div class="col-sm-2">
                            {% if current_user.role == 'Admin' %}
                                <a role="button" class="btn btn-danger btn-sm mt-3 pb-0" data-toggle="modal" data-target="#deleteUserModal">Delete User</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
              </div>
        {% endif %}

        
        

    </section>

</div>

















    <!-- Delete Budget -->
    <div class="modal fade" id="deleteUserModal" tabindex="-1" role="dialog" aria-labelledby="deleteUserModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Delete User?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            
            
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
                    <form action="{{ url_for('users.delete_user', user_id=user.id) }}" method="post">
                        <input class="btn btn-danger btn-sm" type="submit" value="Delete">
                    </form>
            </div>
          </div>
        </div>
      </div>

{% endblock contents %}

app/templates/budgets.html
{% extends "page_template.html" %}
{% block contents %}


    <div class="content">

        <section class="places">

            <div style="float: left;">
                <h1>My Budgets</h1>
            </div>
            
            <div style="overflow: hidden; float: right;">
                <!-- Button trigger modal -->
                <a href="{{ url_for('budgetz.create_budget') }}" style="text-decoration: none;">
                    <button type="button" class="btn btn-outline-info">
                        Request new budget
                    </button>
                </a>
            </div>
                



            <table id="users_table" class="display" style="width:100%">
                <thead style="background: #055041; color: #FFFFFF">
                    <th style="padding: 5px;">Amount</th>
                    <th style="padding: 5px;">Date</th>
                    <th style="padding: 5px;">Name</th>
                    <th style="padding: 5px;">Phone</th>
                    <th style="padding: 5px;">Role</th>
                    <th style="padding: 5px;">Description</th>
                    <th style="padding: 5px;">Status</th>
                </thead>
                <tbody>
                    
                    {% if budgets %}
                    
                        {% for budget in budgets %}
                            {% if budget.phone == current_user %}


                                <tr class="budget_row">
                                    <!-- <td style="padding: 5px;"><a href="{{ url_for('budgetz.budget', budget_id=budget.id) }}" style="text-decoration: none; color: inherit;">{{ budget.amount }}</a></td> -->
                                    <td style="padding: 5px;"><a href="{{ url_for('budgetz.view_budget', budget_id=budget.id) }}" style="text-decoration: none; color: inherit;">{{ budget.amount }}</a></td>
                                    <td style="padding: 5px;">{{ budget.date.strftime('%d-%m-%Y, %H:%M') }}</td>
                                    <td style="padding: 5px;">{{ budget.phone.name }}</td>
                                    <td style="padding: 5px;">{{ budget.phone.phone }}</td>
                                    <td style="padding: 5px;">{{ budget.phone.role }}</td>
                                    <td style="padding: 5px;">{{ budget.bdgt_name }}</td>
                                    {% if budget.status == 0 %}
                                        <td style="padding: 5px;" class="text-center" > <div style="padding: 0; margin: 1px auto;" class="alert alert alert-warning alert-heading" role="alert"> Pending </div> </td>
                                    {% elif budget.status == 1 %}
                                        <td style="padding: 5px;" class="text-center" > <div style="padding: 0; margin: 1px auto;" class="alert alert alert-success alert-heading" role="alert"> Approved </div> </td>
                                    {% elif budget.status == 2 %}
                                        <td style="padding: 5px;" class="text-center" > <div style="padding: 0; margin: 1px auto;" class="alert alert alert-danger alert-heading" role="alert"> Declined </div> </td>
                                    {% endif %}
                                </tr>
                            {% endif %}
                        {% endfor %}
                    
                    {% endif %}
                    
                </tbody>
            </table>







        </section>

    </div>
















      
{% endblock contents %}

app/templates/files.html
{% extends "page_template.html" %}
{% block contents %}

    <div class="content">

        <section class="places">

            <div style="float: left;">
                <h1>Files</h1>
            </div>
           

            <div style="overflow: hidden; float: right;">
                <a href="{{ url_for('filez.create_file') }}" style="text-decoration: none;"><button type="button" class="btn btn-outline-info mt-3 pb-0">Create File</button></a>
            </div>



            <table id="transactions_table" class="display" style="width:100%">
                <thead style="background: #055041; color: #FFFFFF">
                    <th class="text-center" style="padding: 5px;">File No.</th>
                    <th class="text-center" style="padding: 5px;">File Name</th>
                    <th class="text-center" style="padding: 5px;">Subject</th>
                    <th class="text-center" style="padding: 5px;">File Fee</th>
                </thead>
                <tbody>
                    
                    {% if files %}
                    
                        {% for file in files %}
                        <tr class="files_row">
                            <td class="text-center" style="padding: 5px;"><a href="{{ url_for('filez.view_file', file_id=file.id) }}" style="text-decoration: none; color: inherit;"> {{ file.file_no }} </a></td>
                            <td class="text-center" style="padding: 5px;">{{ file.file_name }}</td>
                            <td class="text-center" style="padding: 5px;">{{ file.subject }}</td>
                            <td class="text-center" style="padding: 5px;">{{ file.file_fee }}</td>
                        </tr>
                        {% endfor %}
                    
                    {% endif %}
                    
                </tbody>
            </table>




        </section>

    </div>
























    









{% endblock contents %}

app/templates/side_panel.html
<section class="filters">
                
    <div style="background-color: #055041; height: 48px; border-right: 1px solid #DDDDDD;">
        <p style="text-align: center; line-height: 55px; margin: 0; color: aliceblue;">Budget Files</p>
    </div>

    {% if current_user.role == 'Admin'  %}

        {% if page == 'home' %} 
            <a class="active" href="{{ url_for('users.home') }}">Home</a>
        {% else %}
            <a href="{{ url_for('users.home') }}">Home</a>
        {% endif %}
        
        {% if page == 'approvals' %}
            <a class="active" href="{{ url_for('budgetz.approvals') }}">Approvals</a>
        {% else %}
            <a href="{{ url_for('budgetz.approvals') }}">Approvals</a>
        {% endif %}
        
        {% if page == 'transactions' %}
            <a class="active" href="{{ url_for('transactionz.transactions') }}">Transactions</a>
        {% else %}
            <a href="{{ url_for('transactionz.transactions') }}">Transactions</a>
        {% endif %}

        {% if page == 'users' %}
            <a class="active" href="{{ url_for('users.allUsers') }}">Users</a>
        {% else %}
            <a href="{{ url_for('users.allUsers') }}">Users</a>
        {% endif %}
        
        {% if page == 'budgets' %}
            <a class="active" href="{{ url_for('budgetz.budgets') }}">Budgets</a>
        {% else %}
            <a href="{{ url_for('budgetz.budgets') }}">Budgets</a>
        {% endif %}
        
        {% if page == 'files' %}
            <a class="active" href="{{ url_for('filez.files') }}">Files</a>
        {% else %}
            <a href="{{ url_for('filez.files') }}">Files</a>
        {% endif %}

        
        {% if page == 'register' %}
            <a class="active" href="{{ url_for('users.register') }}">Register</a>
        {% else %}
            <a href="{{ url_for('users.register') }}">Register</a>
        {% endif %}

        {% if page == 'account' %}
            <a class="active" href="{{ url_for('users.account', user_id=current_user.id) }}">Account</a>
        {% else %}
            <a href="{{ url_for('users.account', user_id=current_user.id) }}">Account</a>
        {% endif %}

    {% else %}
    
        {% if page == 'home' %}    
            <a class="active" href="{{ url_for('users.home') }}">Home</a>
        {% else %}
            <a href="{{ url_for('users.home') }}">Home</a>
        {% endif %}

        {% if page == 'transactions' %}
            <a class="active" href="{{ url_for('transactionz.transactions') }}">Transactions</a>
        {% else %}
            <a href="{{ url_for('transactionz.transactions') }}">Transactions</a>
        {% endif %}

        {% if page == 'budgets' %}
            <a class="active" href="{{ url_for('budgetz.budgets') }}">Budgets</a>
        {% else %}
            <a href="{{ url_for('budgetz.budgets') }}">Budgets</a>
        {% endif %}

        {% if page == 'account' %}
            <a class="active" href="{{ url_for('users.account', user_id=current_user.id) }}">Accounts</a>
        {% else %}
            <a href="{{ url_for('users.account', user_id=current_user.id) }}">Accounts</a>
        {% endif %}
        
    {% endif %}


</section>